name: Deploy python package in production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag for the existing (draft) release to publish assets from'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name || github.event.inputs.release-tag || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow-pypi-release:
    name: Publish production PyPI package (JFrog Artifactory, PyPI)
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-release_pypi_assets.yml@main
    with:
      package-name: 'simpeg-archive'
      virtual-repo-names: '["public-pypi-prod", "pypi"]'
      release-tag: ${{ github.event.release.tag_name || github.event.inputs.release-tag }}
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
